kind: Deployment
apiVersion: apps/v1
metadata:
  name: web-express
  labels:
    app: web-exp
  namespace: development

spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-exp

  template:
    metadata:
      labels:
        app: web-exp
    spec:
      containers:
        - name: web-express
          image: kbulix/web-express:latest
          volumeMounts:
          - name: workdir-volume
            mountPath: /storage
          ports:
          - containerPort: 80

      volumes:
        - name: workdir-volume
          hostPath:
            path: /home/devel/dstorage
---
kind: Service
apiVersion: v1
metadata:
  name: web-express-service
  namespace: development
spec:
  selector:
    app: web-exp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort
