kind: Service
apiVersion: v1
metadata:
  name: web-express-Service
  namespace: development
spec:
  selector:
    app: web-exp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort
